# Generated by Django 4.2.10 on 2026-01-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20260121_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
