# Generated by Django 6.0.1 on 2026-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discount_percent',
            field=models.IntegerField(default=10, help_text='Discount percentage for campaign products (0-100)'),
        ),
    ]
