# Generated by Django 6.0.1 on 2026-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
