# Generated by Django 6.0.1 on 2026-01-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='e-Shop', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('contact_email', models.EmailField(default='support@shop.com', max_length=254)),
                ('contact_phone', models.CharField(default='+880 1711 223 344', max_length=20)),
                ('address', models.TextField(default='DHAKA, BANGLADESH')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
